### ISSUE TITLE
[FEATURE] Add delete cheeps in CheepRepository test

### ISSUE THREAD

**Issue by marcusaandahl** [ITU-BDSA23-GROUP11/Chirp#142]
# Issue Description
As a developer, i want to ensure that all the parts of my program work. One function we do not cover is the `DeleteCheep` function in `CheepRepository` (`Chirp.Infrastructure`). This test should be made to ensure it works as intended.

# Criteria
- [x] Add Delete Cheep test
- [x] Ensure it is sufficient to be covered in test coverage
- [x] Ensure it covers the standard test case

**Comment by AndreasBC99** [comment]
It seems the Guid when creating a cheep is null/only zeros. I might need some help to understand why and how to fix it without interfering with the projects functionality.

**Comment by AndreasBC99** [comment]
I've closed the pull request for now. The branch is called `feature/delete-cheeps-test`
