### ISSUE TITLE
Feature - Create Cheep from UI

### ISSUE THREAD

**Issue by VILGITU** [ITU-BDSA23-GROUP11/Chirp#94]
As a user I want to be able to create a Cheep from the User Interface. For now this includes a field for Author and a field for the Message. In the future the Author could be implied from a User-Login (especially since this would prevent users writing Cheeps on others behalf). 

- [x] Input fields for Author and Message
- [x] Sanitation check for length and injection prevention 
- [x] POST request to the database
- [x] Timestamp retrieved from System

**Comment by marcusaandahl** [comment]
No length check needed as it is part of EF restrictions.
